name: Set Secrets to Environment Variables

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set Secrets to Environment Variables
        run: echo "APP_KEY=${{ secrets.APP_KEY }}" >> $GITHUB_ENV
